version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.12
  golang-node:
    docker:
      - image: circleci/golang:1.12-node

jobs:
  install:
    executor: golang
    steps:
      - checkout

      - restore_cache:
          key: v1-gomod-{{ checksum "go.sum" }}

      - run:
          name: Install dependencies
          command: go mod download

      - save_cache:
          key: v1-gomod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

      - persist_to_workspace:
          root: .
          paths:
            - .

  verify:
    executor: golang-node
    steps:
      - attach_workspace:
            at: ~/project

      - run:
          name: Check the style
          command: make style

      - run:
          name: Vet the code
          command: make vet

      - run:
          name: Test dependencies for vulnerabilities
          command: make security

  monitor:
    executor: golang-node
    steps:
      - attach_workspace:
            at: ~/project

      - run:
          name: Update snyk monitoring
          command: make security-monitor

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - install
      - verify:
          context: rel-eng-creds
          requires:
            - install
      - monitor:
          context: rel-eng-creds
          requires:
            - install
          filters:
            branches:
              only:
                - master

experimental:
  notify:
    branches:
      only:
        - master
